/*
 * Copyright (c) 2021-2022 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License")
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
import relationalStore from '@ohos.data.relationalStore';

export class Tools {
  static stringEndWith(origin: string, endString: string): boolean {
    if (origin.length < endString.length) {
      return false;
    }

    let originEndString: string = '';
    for (let index = 0; index < endString.length; index++) {
      originEndString = originEndString + origin[origin.length - endString.length + index];
    }
    return originEndString == endString;
  }

  static getSecurityLevel(securityLevel: string): relationalStore.SecurityLevel {
    switch (securityLevel) {
      case "s1":
        return relationalStore.SecurityLevel.S1;
      case "s2":
        return relationalStore.SecurityLevel.S2;
      case "s3":
        return relationalStore.SecurityLevel.S3;
      case "s4":
        return relationalStore.SecurityLevel.S4;
      default:
        return relationalStore.SecurityLevel.S1;
    }
  }
}
